import type { RollConfig } from "../types";

export const icewindDalePreset: RollConfig[] = [
  {
    id: "extreme-cold",
    name: "Frío extremo",
    icon: "❄️",
    formula: "1d20 + CON",
    description: "Salvación contra frío extremo.",
    type: "save",
    dc: 10,
    visibility: "owner_and_gm",
    target: "active_sheet",
    resultMode: "public",
    effects: [
      { id: "cold-success", condition: "success", message: "Resiste el frío extremo." },
      {
        id: "cold-failure",
        condition: "failure",
        message: "Falla la salvación y gana 1 nivel de agotamiento.",
        updateToken: { field: "cold.exhaustion", operation: "increment", value: 1 },
      },
    ],
  },
  {
    id: "death-save",
    name: "Tirada de muerte",
    icon: "💀",
    formula: "1d20",
    description: "Tirada de salvación contra muerte.",
    type: "death_save",
    visibility: "owner_and_gm",
    target: "active_sheet",
    resultMode: "public",
    effects: [
      {
        id: "death-natural-1",
        condition: "natural_1",
        message: "1 natural: suma 2 fallos de muerte.",
        updateToken: { field: "deathSaves.failure", operation: "increment", value: 2 },
      },
      { id: "death-natural-20", condition: "natural_20", message: "20 natural: recupera 1 punto de golpe." },
      {
        id: "death-success",
        condition: "success",
        message: "Suma 1 éxito de muerte.",
        updateToken: { field: "deathSaves.success", operation: "increment", value: 1 },
      },
      {
        id: "death-failure",
        condition: "failure",
        message: "Suma 1 fallo de muerte.",
        updateToken: { field: "deathSaves.failure", operation: "increment", value: 1 },
      },
    ],
  },
  {
    id: "blizzard-duration",
    name: "Duración de ventisca",
    icon: "🌨️",
    formula: "2d4",
    description: "Duración de una ventisca en horas.",
    type: "normal",
    visibility: "gm_only",
    target: "none",
    resultMode: "gm_only",
    effects: [{ id: "blizzard-result", condition: "always", message: "La ventisca dura el resultado en horas." }],
  },
  {
    id: "foraging",
    name: "Forrajeo",
    icon: "🍖",
    formula: "1d20 + SURVIVAL",
    description: "Buscar comida o recursos en el viaje.",
    type: "save",
    dc: 15,
    visibility: "owner_and_gm",
    target: "active_sheet",
    resultMode: "public",
    effects: [
      { id: "foraging-success", condition: "success", message: "Encuentra recursos útiles." },
      { id: "foraging-failure", condition: "failure", message: "No encuentra recursos útiles." },
    ],
  },
  {
    id: "frost-accumulation",
    name: "Escarcha acumulativa",
    icon: "🧊",
    formula: "1d20 + CON",
    description: "Regla casera para acumular escarcha por exposición extrema.",
    type: "save",
    dc: 10,
    visibility: "owner_and_gm",
    target: "active_sheet",
    resultMode: "public",
    effects: [
      { id: "frost-success", condition: "success", message: "Resiste la escarcha." },
      {
        id: "frost-failure",
        condition: "failure",
        message: "Acumula 1 punto de escarcha.",
        updateToken: { field: "cold.frost", operation: "increment", value: 1 },
      },
    ],
  },
];
